### ISSUE TITLE
URLs for multilingual web sites

### ISSUE THREAD

**Issue by seleckis** [getkirby-v2/kirby#124]
It would be great to add ability to change URLs of pages in multiple languages.
E.g.
In English: `/blog/i-need-kirby`
In Russian: `/ru/блог/мне-нужен-кирби`
In German: `/de/blog/ich-brauche-kirby`
etc.

**Comment by seleckis** [comment]
Hello, here is forked kirby starterkit: https://github.com/seleckis/kirbycms-url-bug
Instruction provided in readme.

**Comment by bastianallgeier** [comment]
That's super helpful! I won't be here next week, but I'll try to fix this asap as soon as I'm back.

**Comment by bastianallgeier** [comment]
This is possible in v3
