### ISSUE TITLE
Text file for missing/renamed image taken as text file for content

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#207]
Just renamed some images via file systems but didn't rename the respective meta files. What happened was that all of a sudden my text file contents seemed to have disappeared until I realized that Kirby just took the next best text file which happened to be one of the stray image meta files ...

**Comment by lukasbestle** [comment]
Yeah, that's a difficult problem. Unfortunately, that's just how Kirby works, since the name of the text file determines the template to use and Kirby can't know which one it the correct one.

Though, what could be a solution is to "guess" that every text file with

- two dots in the filename
- a "second" file extension being a file extension known to Kirby for files

is a metadata file. I'm not sure if that would break something.

**Comment by texnixe** [comment]
Yeah, you're right, it's difficult to sort that out and I wouldn't go for the two-dot-solution, because people might use more than one dot for their content files on purpose. The second solution seems more feasible. I don't even know if it is a problem that needs attention but wanted to record it for reference in case anyone comes across this problem.

**Comment by lukasbestle** [comment]
Using dots for template names on purpose is not going to work reliably anyway (when enabling multi-language support, it would all collapse). So I think that a combination of the two approaches could actually work (if I didn't miss something).

I think that this is actually an issue that should be solved if possible, as that simple change of renaming a file can lead to results that are very difficult to understand and to track down.

**Comment by FabianSperrle** [comment]
This happened to me too, yesterday.

> Yeah, that's a difficult problem. Unfortunately, that's just how Kirby works, since the name of the text file determines the template to use and Kirby can't know which one it the correct one.

Well, I don't have either a template nor a blueprint with the name of the metafile, but of course with the same name as the actual content file. While this might not always be the case kirby could try to find the correct file like that before falling back to alphabetical order (or whatever it does to get a file...).
