### ISSUE TITLE
"Invisible" folder masks a "visible" folder with the same name when filtering children using visible() 

### ISSUE THREAD

**Issue by peterkelm** [getkirby-v2/kirby#241]
Imagine you have two folders named _someFolder_ and _01-someFolder_ and want to loop over all visible subpages as below:

...foreach($page->children()->**visible()** as $section) {...

Despite having a name starting with a number foreach would **skip** content from the folder  _01-someFolder_ if another folder using the same (base) name, i.e. _someFolder_ in this example, exists in the same (parent) directory.

Bug or feature? If the latter - where is that behavior documented?

Using Kirby 2.0.6 on OS X 10.10

Peter

**Comment by texnixe** [comment]
You can't have two folders with the same name even if one of them has a prepended number. Both would result in the same URL and that's not possible

**Comment by peterkelm** [comment]
I agree. In fact, it seems like a Kirby design decision to **drop both folders** in such a situation (to prevent ambiguity). Yet, from the file system's perspective these folders do not have the same name, so there's no conflict whatsoever.

**Just creating a folder with the "wrong name" is an interesting way to take a web page (or parts of it) offline.** Took me a while to figure out is was that folder name conflict. I expected that the folder with the number prefix takes precedence over the non-prefixed folder. That would also resolve the ambiguity issue. Either way, the **workaround** is simple: **Make sure that content folder names are unique, regardless of a prepended number.**

Would be great to see this behavior documented officially in an appropriate place. Also, a clear entry in the web server/php log would have helped.

**Comment by texnixe** [comment]
I admit the information is probably a bit indirectly expressed on this page http://getkirby.com/docs/content/adding-content where it states that the URLs are built from the folder's base name. Maybe that should get a bit more focus; I can remember having come across this issue before ...
