### ISSUE TITLE
Thumbs filename, width and height not working like expected

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/kirby#274]
http://forum.getkirby.com/t/thumbs-filename-width-and-height-not-working-like-expected/1645

``` php
c::set('thumbs.filename','{safeName}-{width}x{height}.{extension}');
```
### Expected

```
my-filename-300x150.png
```
### In real life

```
my-filename-300x.png
```
### Here is why

When creating the thumbnail I let the thumb calculate the height.

``` php
thumb( $page->image(), array('width' => 300) );
```

However I still expect it to rename the file by the size even if I don't set it.
### Bug or feature?
- Is how it work now expected behaviour?
- Will it be changed in the future to reflect the image size, not the function call?
- If not, can we add another height-value, like "autoheight" to have the height in the filename even if it's not set by the template?

**Comment by Ascarius** [comment]
The calculated height could certainly not be part of the resized file name, since we need to be able to check resized file existence (caching) without calculating on original image.

**Comment by jenstornell** [comment]
@Ascarius I did not think about that but you are right. The image ID will break if the filename changes that way.

I still want this to look ok and it will if the x is removed when no height is set. That would require some kind of condition in the config name setting.
