### ISSUE TITLE
Default language not respecting URL-Key makes themes complicated

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby-v2/kirby#295]
In a multilingual setup, It seems that `URL-Key` is always ignored by the default language -which in return always will require changing the content folder names in conjunction to the default languages, correct? why is this? 

Because, if URL-Key was respected even against the default language, it would make themes a ton more flexible as it would only require changing the config.php supporting both single and multiple languages easier regardless of the content folder-names :grin:

So instead of brewing up a theme with content for each possible default language in the world, they could simply always stay english.

Maybe I'm just looking at it in a wrong way?

**Comment by zyre91** [comment]
I'm also looking for clarification on this. I would have expected URL-Key to work for any language, regardless of which language is the default.
At the moment I have to name the folders to whatever the default language of the site should be, which can be a bit difficult to work with if you don't speak the language.

**Comment by PaulMorel** [comment]
If you're comfortable with modifying a couple of core files, I managed to get it working by commenting out  a couple of lines.

`kirby/branches/multilang/page.php` has a public function called `slug()` which includes 2 checks for `defaultLanguage()`. Comment out lines 80-82 and 96-98.

@bastianallgeier Correct me if I'm wrong, but if it's that simple of a fix, I could do a Pull Request with my changes

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by frankrausch** [comment]
Agreed. If there is no significant performance hit (or other internal reason to avoid the extra check in the default language), I would also prefer a consistent behavior for `URL-Key:` across all languages.

**Comment by texnixe** [comment]
@bastianallgeier, @distantnative : Is this on the agenda for the upcoming release?

**Comment by distantnative** [comment]
As I just discussed with @texnixe, I can already think of two sides to this issue:

1. The core: I think this could be rather easily implemented. Maybe optional.
2. The panel: Editing the slug for non-default languages in the panel changes the `URL-Key`. However, editing the slug on the default language moves/renames the content directory. So at the moment, there is no UI component which could allow renaming the content directory as well as changing the URL-Key independently of the default language. This one seems rather tricky.

**Comment by bastianallgeier** [comment]
It also has effects on performance. Right now all page::find calls will just look for the folder name unless you specificly search for a translated URL. This has a huge impact on performance instead of having to open each text file.

**Comment by texnixe** [comment]
> It also has effects on performance

Yes, I agree that could become a problem that has already been discussed in several other contexts.

On the other hand, it would allow for changing the default language without having to rename all folders and to use standard folder names in English even if the default language is another language. The question is (as always), how big this impact really is, considering that we filter by all sort of content all the time anyway, where Kirby also has to read all the files. 

Maybe if this is just an option and not a default behavior, then it is for developers to decide if they sacrifice performance for the feature?

**Comment by felixbridell** [comment]
Would be really great to have this as an option in the config.

**Comment by matkovsky** [comment]
It would be awesome to have this option.

Since there is no way of overriding the `Page` class' `slug()` method without hacking (a.k.a. commenting out the `if($current == $default)` parts), this option needs to be implemented in the core.

But if there's a way to add this functionality without changing the core files (so I could safely update Kirby in the future), please let me know what I'm missing. 😢 

Thanks.

**Comment by barnabas-szekeres** [comment]
By the way commenting out the slug function's parts not a good idea if you had installed Kirby via Composer. 

Is there any other solution or workaround for this issue?

**Comment by lukasbestle** [comment]
This feature won't be part of Kirby 2, but we are planning to introduce a more robust multilang implementation with Kirby 3 that will probably have this feature. :)
