### ISSUE TITLE
Accent insensitive search?

### ISSUE THREAD

**Issue by eroonkang** [getkirby-v2/kirby#304]
Currently, there's no way to create case insensitive search, as discussed [here](https://forum.getkirby.com/t/to-create-accent-insensitive-search/2196) in the Kirby forum.

> Let's say you have a post tiled "my new résumé".
>   If you run a site wide search with /?q=résumé , the post would show up, whereas /?q=resume would not.

Would be great to have this capability in the next release.

**Comment by malvese** [comment]
This would be particularly useful for languages with umlauts, accents…
French is full of accents, and lots of people don't bother typing them when they search. Probably because Google search ignores them, so they got used to that behaviour.
