### ISSUE TITLE
Partial caching

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/kirby#311]
If you enable the cache, no template code will be run after the first visit. Sometimes it can be useful to have areas of the page that are still dynamic. Currently, you would need to disable the cache completely.

A possible solution could be to include this dynamic PHP code in the cached HTML. Instead of sending the cached file to the browser, Kirby would `include` the file so that the PHP code runs.
Running the code on the first visit as well could be done by using the evil `eval`, but I don't think we should go this route at all. Alternatively, Kirby could first store the cached HTML/PHP mix and then read it again from the cache on the first visit, but that's not that awesome regarding performance.

I proposed a feature like this in Kirby 1 times already, but the solution back then wasn't stable and secure at all, maybe we can try again. :smile:

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by distantnative** [comment]
What are your ideas on how to markup what PHP code should actually be cached and which parts need to stay dynamic?

**Comment by lukasbestle** [comment]
My idea back then was to echo PHP code like this:

```php
echo "<?php echo 'somedynamicvalue'; ?>";
```

Not very elegant and Kirby-like though.

**Comment by jolantis** [comment]
Hi, what's the status of this idea of partial caching? It's something that would help me using cache in combination with running mobile detect.

I include a dektop or mobile header/footer snippet based on device detection. The mobile detect function sets a device class session variable.

When caching (memcached) is enabled this session variable is either ‘desktop’ or ‘mobile’, not on or the other depending on visiting the site/page with a mobile or desktop device. Either the ‘mobile’ or ‘desktop’ version of the header/footer snippet is included (depending in which device class is visited first and therefore cached).

Excluding snippets, functions and/or parts of templates from being cached would definitely help in this example…

**Comment by rmngrc** [comment]
Are there any plagins to bring this to Kirby in a near future?

**Comment by lukasbestle** [comment]
Not in the near future. There is still no really great and solid technical solution for this.

**Comment by iv-craig** [comment]
Could the [Kirbytext pre/post filters](https://getkirby.com/docs/advanced/kirbytext#kirbytext-filters) work as a basis for building this? Plugins are loaded before render() in the launch() method, so after retrieving the cached page you could perform whatever functions you want that have been defined in a plugin:

```
cache::$post[] = function($cache, $value) {

  $snippets = c::get('cache.snippets', array());
  $values   = array_values($snippets);
  $keys     = array_map(function($key) {
    return '{{' . $key . '}}';
  }, array_keys($snippets));

  return str_replace($keys, $values, $value);

};
```

More complex dynamic content would need something more than that within the plugin, but as long as the filter is available that would be up to the user.

**Comment by ezraverheijen** [comment]
Fragment caching is the way to go here. Not caching entire pages and trying to exclude certain dynamic parts of those pages, but caching parts of pages and include those cached parts inside the dynamic pages. Kind of snippets inside snippets.

See https://css-tricks.com/wordpress-fragment-caching-revisited/ and https://markjaquith.wordpress.com/2013/04/26/fragment-caching-in-wordpress/ for ideas on how it can be done in WordPress.

The biggest WordPress caching plugin, W3 Total Cache, also supports fragment caching and uses some sort of security for this, explained in short here: https://www.justinsilver.com/technology/wordpress/w3-total-cache-fragment-caching-wordpress/
I haven't looked into the plugin's code, but this could provide some useful info on how to secure this kind of caching.

**Comment by lukasbestle** [comment]
Fragment caching is already possible, see [this topic in the forum](https://forum.getkirby.com/t/cache-part-of-a-page/5199?u=lukasbestle). But fragment caching is something that people will have to use deliberately, it's not done with a simple Kirby option that can be switched on or off.
