### ISSUE TITLE
Add "full phrase" feature to `$pages->search()`

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/kirby#313]
See [this topic in the forum](https://forum.getkirby.com/t/how-to-use-search-to-include-multiple-words/2400).

**Comment by SQbiz** [comment]
It looks like this might be possible with only a little modification. Instead of splitting the string on all spaces, use a regex to split the query only on spaces *not within* quotations:

*search function in core/pages.php*
```
    // $searchwords = preg_replace('/(\s)/u',',', $query);
    // $searchwords = str::split($searchwords, ',', $options['minlength']);

    preg_match_all('/[^\s"\']+|"([^"]*)"|\'([^\']*)\'/', $query, $searchwords);

    $searchwords = $searchwords[0];
    for ($i = 0; $i < count($searchwords); $i++) {
      $searchwords[$i] = trim($searchwords[$i], '"\'');
    }
```

example:
`these are my "search terms"`&rarr;
```
array (size=4)
  0 => string 'these' (length=5)
  1 => string 'are' (length=3)
  2 => string 'my' (length=2)
  3 => string 'search terms' (length=12)
```

Could still be improved: RIght now this regex includes the quotes within what is captured, hence the subsequent trimming `for` loop

Does not play well with single quotes:
`Chance the Rapper's "No Problem (feat. Lil Wayne & 2 Chainz)"`&rarr;
```
array (size=5)
  0 => string 'Chance' (length=6)
  1 => string 'the' (length=3)
  2 => string 'Rapper' (length=6)
  3 => string 's' (length=1)
  4 => string 'No Problem (feat. Lil Wayne & 2 Chainz)' (length=39)
```

**Comment by SQbiz** [comment]
I should also note that I came across this problem when a client used quotations in a search term - the quotes were not escaped, so the pagination links were broken:

```
<a class="pagination-button" href="/search/page:2?q=" my quoted search"">
```

I fixed this with by wrapping all of my pagination links in `urlencode()`:

```
<a class="pagination-button" href="<?= "/search/page:" . $num . $filter_url . "?q=" . urlencode($query) ?>">
```

I could have been smarter and used single quotes, but then a search term `'like this'` would have done the same thing.

**Comment by SQbiz** [comment]
While we're on the subject, it would be nice to have the option to require **all** of the terms are matched somewhere across the searched page

**Comment by lukasbestle** [comment]
Thank you for your effort. We might consider this feature in the future.

Have you considered using Algolia with the [Algolia plugin](https://github.com/getkirby-plugins/algolia-plugin)? They allow much more advanced queries and return very good results.

**Comment by SQbiz** [comment]
I hadn't seen Algolia, that looks good, thanks!

**Comment by lukasbestle** [comment]
Example implementation for this feature: https://gist.github.com/lukasbestle/f63b32c4194c7e727ff9

+1 for the feature from @malvese.
