### ISSUE TITLE
kirbytext unsupported parameter breaks tag

### ISSUE THREAD

**Issue by puckey** [getkirby-v2/kirby#323]
I had a tag break in a weird way, because I miswrote the parameter name.

If the tag should be written like:

```
(embed:https://vimeo.com/123456 ratio:4/3 text:this is a text)
```

But I miswrite it by accident:

```
(embed:https://vimeo.com/123456 ratio:4/3 textmistake:this is a text)
```

The ratio parameter now contains the following string:

```
4/3 textmistake:this is a text
```

Causing the tag to break.

I would prefer that either:
- an error is thrown when a parameter is used which is not supported by the tag
- or the unsupported parameter is swallowed, instead of having its contents added to another parameter

**Comment by lukasbestle** [comment]
> or the unsupported parameter is swallowed, instead of having its contents added to another parameter

I think that this can be quite confusing. Let's say you have a `text` attribute and you want your users to put in arbitrary text. If that text includes a colon, the result would be that the rest of the tag is discarded.

**Comment by bastianallgeier** [comment]
I'm still not 100% sure about this either. Is it really better to throw an error? Swolloing the parameter is not really possible I think, but I will double-check.

**Comment by lukasbestle** [comment]
If you decide to go the error route, I'd instead echo a warning when the `debug` option is set to `true`. Then such stuff can be found while developing.
