### ISSUE TITLE
Pre-generated thumbnails

### ISSUE THREAD

**Issue by raphaelokon** [getkirby-v2/kirby#329]
Hi.
I am currently evaluating Kirby locally – I have to admit it is really awesome! Great work. I have one essential questions tho:

I think it would be cool if you could set the thumbnail sizes for images in the `config.php` and auto generate those on the fly when uploading an image to a page. I am using four different sized thumbs with a `srcset` and the initial page load is really slow (due to thumbs creation). Can those thumbs be pre-generated?
Or is there a way to warm up the cache, so that pages with a lot of computation-heavy ~~pages~~ actions (like creating thumbnails) load faster on initial load?

**Comment by distantnative** [comment]
Once the thumbnails are created (first page load by anyone) they should be available for everyone without delaying their initial page load.

**Comment by texnixe** [comment]
You can also use a hook that is triggered on panel.file.upload that creates differently sized thumbnails before they are used in a template. I think their is also a plugin that does that, check out http://getkirby-plugins.com

**Comment by nordisk** [comment]
@texnixe Oh that would be great really! If you could point me to any documentation or that specific plugin.
@distantnative Yeah … I know, still the thumbnails should be generated beforehand based on some global config.

**Comment by texnixe** [comment]
Documentation on hooks: http://getkirby.com/docs/panel/developers/hooks

Basically, it's just sth like this:

```php
kirby()->hook('panel.file.upload', function($file) { 
  $file->resize(300);
  ));
});
```

**Comment by bastianallgeier** [comment]
This is actually something I want to add to the panel as an option for uploads. Not sure in which version it will be arriving though. The hooks are a great temporary solution in the meantime.

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by nordisk** [comment]
@bastianallgeier Cheers! Thanks for the mention of the hooks @texnixe.
:+1:

**Comment by nordisk** [comment]
Hi all.

Is there a way to also make that happen when I upload the images manually eg. through FTP?

**Comment by samvantoever** [comment]
@texnixe I tried your code and watched the thumb folder, but whenever I add a file it removes all the previously generated thumbnails. Is there a way to keep those previously generated thumbnails?

**Comment by raphaelokon** [comment]
@texnixe Same here.

**Comment by texnixe** [comment]
But even more strange, it generates additional thumbs with a size that is not defined anywhere. See also this issue:https://github.com/getkirby/panel/issues/863

**Comment by samvantoever** [comment]
Is there any news regarding this issue?

**Comment by samvantoever** [comment]
P.S. @texnixe I think the additional thumbs are created because of the files sidebar. See: https://github.com/getkirby/panel/blob/master/app/snippets/pages/sidebar/file.php

**Comment by texnixe** [comment]
@samvantoever: Yes, you are right, those thumbs are created from the sidebar.

**Comment by samvantoever** [comment]
After digging through the source code I've found the cause of this issue.

I don't know for what reason, but all the thumbnails are removed on purpose when uploading a file. See the following file on line 66: https://github.com/getkirby/panel/blob/master/app/src/panel/models/page/uploader.php

This removeThumbs() function is also called a few times within:
- https://github.com/getkirby/panel/blob/master/app/src/panel/models/file.php
- https://github.com/getkirby/panel/blob/master/app/src/panel/models/page.php
