### ISSUE TITLE
User profile field methods not working

### ISSUE THREAD

**Issue by afbora** [getkirby-v2/kirby#333]
User profile field methods not working: `kirbytext()`, `int()`, `isEmpty()` or custom method and etc..
### Examles:

``` php
site()->user('admin')->about()->kirbytext();
site()->user('admin')->age()->int();
site()->user('admin')->avatar()->isEmpty();
```
### Error:

> Fatal error: Call to a member function kirbytext();

**Comment by bastianallgeier** [comment]
I thought some more about this and actually it's something that needs more consideration and isn't really a bug but more a missing feature. I will try to solve this in 2.3

**Comment by afbora** [comment]
I'm using like following for now:

````php
kirbytext(site()->user('admin')->about());
````

*instead of*

````php
site()->user('admin')->about()->kirbytext();
````

**Comment by LeBenLeBen** [comment]
If that can be of any help, you can create fields based on user data with:

```php
structure($user->data())
```

**Comment by bastianallgeier** [comment]
This is fixed in v3
