### ISSUE TITLE
Cache whitelist option

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/kirby#346]
See [this topic in the forum](https://forum.getkirby.com/t/partial-caching-on-the-fly/2837/2?u=lukasbestle). 
Proposal: Instead of _ignoring_ pages, _only_ cache specified pages from a config whitelist.

**Comment by distantnative** [comment]
Works like this: as long as `cache.whitelist` is empty, cache all pages that are not in `cache.ignore` - if `cache.whitelist` has any entries, only cache these (except they are also in `cache.ignore`)?

**Comment by lukasbestle** [comment]
Sounds good.

**Comment by distantnative** [comment]
Thinking of something like this:

```php
// core/page.php

  public function isCachable() {

    // The error page should not be cached
    if($this->isErrorPage()) {
      return false;
    }

    // whitelist
    $whitelist = $this->kirby->option('cache.whitelist');
    if(is_array($whitelist) and count($whitelist) > 0) {
      foreach($whitelist as $pattern) {
        if(fnmatch($pattern, $this->uri()) === true) {
          return true;
        }
      }
      
    // ignore list
    } else {
      foreach($this->kirby->option('cache.ignore') as $pattern) {
        if(fnmatch($pattern, $this->uri()) === true) {
          return false;
        }
      }
    }

    return true;

  }
```

Still need to test it.

Also thinking about which one of the two options has the final say.

**Comment by distantnative** [comment]
Do we have a better word than `whitelist` for this? Something that matches `cache.ignore`?

**Comment by lukasbestle** [comment]
Maybe we could rename `cache.ignore` to `cache.blacklist` in the future (the old version would still be supported for backwards-compatibility). I think that would be easier to understand.

**Comment by distantnative** [comment]
Related to #146.
