### ISSUE TITLE
Extending panel hooks or append new hooks

### ISSUE THREAD

**Issue by afbora** [getkirby-v2/kirby#347]
`panel.page.create` hook doesnt work with `$page->create()` function.

`panel.*` hooks great but i think, its should be without `panel.` hooks like that:

> page.create
> page.update
> page.delete
> page.sort
> page.hide
> page.move
> file.upload
> file.replace
> file.rename
> file.update
> file.sort
> file.delete
> user.create
> user.update
> user.delete
> avatar.upload
> avatar.delete

For example:

`page.create` hook works with `creating from panel` and `$page->create() function`

Or both method can be use like `page.create` and `panel.page.create`.

**Comment by afbora** [comment]
PR about this issue: https://github.com/getkirby/kirby/pull/348

**Comment by thasmo** [comment]
I think the `panel` namespace makes total sense, e.g. when hooks get triggered from plugins where they are definitely not called by using the panel, the namespace could be a different one, like `api.page.create` or similar. So, for future changes in general I would keep the `panel` namespace.
