### ISSUE TITLE
filterBy() Inconsistency for toggle and checkbox field 

### ISSUE THREAD

**Issue by m-artin** [getkirby-v2/kirby#387]
> The behavior of the checkbox field and the toggle field is not consistent. 

for the toggle field: true/false
for the checkbox field: 1/0

Template example:

```
<?php foreach($page->images()->filterBy("imagevisible", "==", "1") as $image): ?>  
    <div class="image">  
          <img src="<?= $image->url() ?>">  
     </div>  
<?php endforeach ?>
```

[See Kirby Forum](https://forum.getkirby.com/t/fetch-images-from-children-that-have-certain-metadata-applied-to-them/3095/9)

**Comment by bastianallgeier** [comment]
This is fixed in v3
