### ISSUE TITLE
Coding Style: Use Type Hints

### ISSUE THREAD

**Issue by FabianSperrle** [getkirby-v2/kirby#388]
In my opinion, kirby should introduce type hints in the core, the panel and the toolkit. I compiled a small lists with a few reasons, your feedback is welcome!
- The resulting code is type safe. This is be most obvious result, but not to be overlooked. Typesafe code can prevent many issues, especially with respect to APIs where other developers use the code, and are less familiar with it.
- The resulting code is easier to understand. Just this morning I was digging through panel, core and toolkit code hunting a bug. Currently there are lots of methods that take a few arguments like `$parent`, `$model`, etc where it was not immediately obvious to me which type those arguments had.
- The resulting code is easy to edit with IDEs. This goes hand in hand with the second point. When the IDE knows what type a variable has, it can offer convenience features (code completion, jump to declaration, ...)
- PHP7 finally introduced scalar type hints. While it will probably be a long time until PHP7 is a requirement for kirby, this could be a first step in that direction.

**Comment by bastianallgeier** [comment]
We do this extensively in v3
