### ISSUE TITLE
Make multilang routes easier

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/kirby#396]
See [this topic in the forum](https://forum.getkirby.com/t/routes-in-multi-lang-setup/3487?u=lukasbestle).

There should be a feature that helps with matching multilang routes. Maybe an option for the route (`'multilang' => true`) that then modifies the pattern and handles the result so that the language code is always passed as the first argument, even if the URL doesn't contain it (default language)?

**Comment by jenstornell** [comment]
+1

**Comment by texnixe** [comment]
+1

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by p-h-i-l** [comment]
:+1:

**Comment by nocksock** [comment]
Ran into this today, found the [forum post](https://forum.getkirby.com/t/routes-in-multi-lang-setup/3487/9) and then this issue. Adding my vote!

+1

**Comment by samnabi** [comment]
+1

**Comment by krisak** [comment]
+1

**Comment by jolantis** [comment]
+1

**Comment by peterkelm** [comment]
+1 

👍

**Comment by rzschoch** [comment]
+1
