### ISSUE TITLE
Adding colorize parameter to thumb

### ISSUE THREAD

**Issue by Ventricule** [getkirby-v2/kirby#406]
Hello,
Why not adding colorize parameter to thumbs ?
Almost the only thing to do is to add 

```
if($thumb->options['colorize']) {
       $img->desaturate()->colorize($thumb->options['colorize'], 1);
}
```

in toolkit/lib/thumb.php l.340

And something similar for imagick

**Comment by jenstornell** [comment]
The reason I don't like this idea is that it's no end to this feature. It's possible to add unlimited kind of filters and adjustments.

The only thing I maybe would like is to turn an image black and white. Everything else is a range of stuff.

With CSS and canvas there are possibilities to make these things with a tiny javascript:

http://alexmic.net/filtrr/

Resize and crop is used to fit the layout of the site but everything that has to do with image enhancements I think belong to an image application like Photoshop.

However I think it would be an awesome plugin, but not a core feature.

**Comment by texnixe** [comment]
I agree with @jenstornell on this one. Extentions to the thumb method would probably make more sense in a plugin considering that there are so many possible options.

**Comment by Ventricule** [comment]
I understand your position. True thats it's no end to this feature. But because the thumbs builder is based on simpleImage, I'm sure there is a simple way to pass all parameters from thumb() to simpleImage, in an elegant way.
Anyway, I tried the capacity of php to colorize images, and its a bit disappointing, the colors are dirty.
I'm not really convinced by the use of javascript in my case — because it make more sens to generate the image one time rather than each page load — but I will try it.
