### ISSUE TITLE
Add a LICENSE file with relevant information

### ISSUE THREAD

**Issue by fvsch** [getkirby-v2/kirby#410]
It’s a common “best practice” for publicly distributed software to come with a license document that spells out what end users may or may not do with the software. It might be a good idea to provide one in this repository, preferably using clear language and without resorting to excessive legalese.

Maybe something like:

```
Copyright (C) 2012-2016 by Bastian Allgeier / Bastian Allgeier GmbH

KIRBY TRY-OUT LICENSE

This license allows users to download the source code for Kirby CMS
(https://github.com/getkirby/kirby) and install it freely and free of charge on:
- a local machine, or
- a private test server.

If you are happy with Kirby CMS and want to use it to power a public-facing
website or web service (including but not limited to: communication websites,
personal sites, portfolios, intranets, documentation sites), you must buy a
license from https://getkirby.com/buy before publishing your website using
Kirby CMS. Licenses are available for both personal and professional uses.

More information:
https://getkirby.com/try
https://getkirby.com/blog/free-trial

A use case for Kirby which does NOT require buying a license:
https://getkirby.com/blog/prototyping-with-kirby
```

**Comment by texnixe** [comment]
There is in fact a license document, only it is not distributed with the single repos but only with the kits.

**Comment by fvsch** [comment]
Oh, I had missed it, my mistake.

That license is a bit strange. It would make perfect sense if it was distributed only when buying a license key. But as it stands, people can download the starterkit and install it and they get a document which says “great, now you have a license, you can use the software on ONE site, if you want to use it an another website you have to buy another license” (paraphrasing). Kinda sounds like people get a free license for one production site.

That license would be 1) stronger if it had a Condition clause that said "hey this license is only valid for production websites if you have bought and configured a LICENSE KEY, so please do that" and 2) if it had a friendly intro that summed up how this thing works in plain language.

(It probably shows but: I am not a lawyer.)
