### ISSUE TITLE
function user->exists()

### ISSUE THREAD

**Issue by atimoda** [getkirby-v2/kirby#458]
The docs of the function $user->exists() says that it returns a boolean. But in my tests, it only return true (if exists) or throw an Exception if dont. It should return false in the case that dont exists (this is what the docs says, and what I think its right too).
https://getkirby.com/docs/cheatsheet/user/exists

**Comment by lukasbestle** [comment]
It's not `$user->exists()` that throws the exception but creating the user instance. The error is thrown in the constructor.

Nonetheless, it shouldn't be this way. I don't know if it can really be fixed though as existing code might be relying on the exception in the constructor.

You can do so as well until this is fixed:

```
try {
  $user = new User($username);
} catch(\Exception $e) {
  $user = false;
}
```

**Comment by texnixe** [comment]
Think we should either fix this or remove the `exists()` method from the user class and the docs.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
