### ISSUE TITLE
excerpt()  word count does not work correctly if text contains special characters

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#466]
See this post: https://forum.getkirby.com/t/excerpt-word-count-how-does-it-work/4473/9

**Comment by 11bits** [comment]
Any news on this issue?

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
