### ISSUE TITLE
YAML for data storage

### ISSUE THREAD

**Issue by Sija** [getkirby-v2/kirby#472]
Why not use _YAML_ for all data storage? 
That would help with issues like #470.

**Comment by lukasbestle** [comment]
As I wrote in the other issue, YAML would make the syntax more complex and harder to write by hand (indentation and quoting issues are very common for YAML as we regularly see in the forum).
I'm going to leave this open for discussion however.

**Comment by Sija** [comment]
It's a widely used format (see: Jekyll, ...) for text-related use cases — that was the sole reason of its inception. Also, there's plenty of references and other help to assist users in grokking the intricacies of quoting for instance. Creating another format to "fix" it seems like an NIH syndrome to me ;)

**Comment by bastianallgeier** [comment]
There are two major reasons for our custom format. 

1. simplicity. Kirby started as a system without web interface and many still use it without the panel. It's in fact one of our strengths that the panel can simply be removed. For simple editing, our format is much more easy to understand and type than YAML — especially for non-techie people. 

2. performance! It's incredibly simple to parse our format and it's definitely much faster than parsing YAML. 

I was thinking about a switchable parsing engine though. It would actually be quite simply to replace the parsing part with a different format. So maybe this could become a config option some day.

**Comment by lukasbestle** [comment]
...or we could make this a Kirby component that can just be replaced completely.

**Comment by bastianallgeier** [comment]
Good idea!
