### ISSUE TITLE
camelCase in Blueprint seems to be not working

### ISSUE THREAD

**Issue by visualcookie** [getkirby-v2/kirby#473]
Hi,

I've recently discovered an issue with camelCase naming for Blueprints. When I've uploaded my Kirby to a live server, I couldn't select the Blueprints written in camelCase. Works for Local.

**Server:**
PHP version 5.6.20
Debian 8

**Local:**
PHP version 5.6
Windows

**Comment by jenstornell** [comment]
I always write filenames in lowercase and uses `-` as separator. So maybe this is not an issue but a best practice recommendation, to always use lowercase?

**Comment by visualcookie** [comment]
Hmmm... yeah. That's the way I did it know, since this seems to be not working on Linux. So it's an OS kind of problem.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
