### ISSUE TITLE
Add model method to Page

### ISSUE THREAD

**Issue by pedroborges** [getkirby-v2/kirby#478]
I've had some issues with page models not working inside hooks. Adding a `model` method to the Page object be very useful for plugin developers. See: getkirby-plugins/algolia-plugin#3

**Comment by lukasbestle** [comment]
As pages inside the CMS are always instances of the model, I think this should only be part of the page objects inside the Panel. That page object could then be passed to hooks by default without requiring to use the method manually.

**Comment by bastianallgeier** [comment]
Sorry guys, but you need to explain this closer to me. I don't really get it. Or maybe @lukasbestle has to implement it :)

**Comment by lukasbestle** [comment]
Yes, I can implement this.

Quick explanation: Sometimes you need "proper" page objects inside the Panel, e.g. in hooks. We would add a new `->model()` method to the Panel `Page` class that would load the page model and return the model page object for the page.

**Comment by bastianallgeier** [comment]
Hm, shouldn't we just load models in the panel or do you think this is going to create too many conflicts.

**Comment by lukasbestle** [comment]
Yes, I think so. The Panel classes have so many custom methods just for the Panel. If they would all be overridden by the model classes, it would break the Panel (and would be very hard to debug).

**Comment by bastianallgeier** [comment]
Maybe we should think about a more solid way to separate extended page models for the panel and the regular ones. I think we should move this to 2.5 to be honest and have a closer look at it first.

**Comment by bastianallgeier** [comment]
I'm not sure introducing yet another core page method is such a good idea as an alternative.

**Comment by lukasbestle** [comment]
+1 for moving this to 2.5. I'm not sure about the separate Panel page models though. But that's exactly why we need to discuss it after 2.4 is done.

**Comment by lukasbestle** [comment]
We should probably think about making feature overrides with models much more specific in v3. Meaning: Allow overriding field methods, allow overriding CRUD functionality (see #614) etc.
Maybe it isn't such a good idea to allow overriding *any* page method. Overriding core methods breaks a lot of stuff. So definitely something we need to keep in mind when redesigning the page model feature in v3.
