### ISSUE TITLE
Add HTTP/2 server push link headers for assets

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/kirby#499]
We could extend the `css()` and `js()` helpers to set an HTTP link header for each printed style/script tag. Issue: The list of assets needs to be stored in cache, otherwise the headers will be missing if the page is loaded from Kirby's cache.

**Comment by HashandSalt** [comment]
Hi @lukasbestle Did anything happen with this? I'm wanting to implement this on my site, is there a way to do it? I am not using the cache so that part is not important to me.

**Comment by lukasbestle** [comment]
As the cache in Kirby 2 doesn't support headers, we won't be able to implement this properly (if we do it, it needs to be compatible with every site). In Kirby 3 however it might be doable. We will look into this, but probably after the initial v3 release.

In the meantime, you can either manually set the header with the PHP `header()` function or you can create a custom `css/js` Kirby component that does this automatically and put it in the `plugins` directory.
