### ISSUE TITLE
File next method doesn't take in account sort order

### ISSUE THREAD

**Issue by CelineDesign** [getkirby-v2/kirby#502]
I have the following blueprint :
files:
  type: image
  sortable: true
  fields:
    title:
      label: Titre
      type: text

I've ordered my files in the panel.
But the $file->next() methods returns the next file by filename and not by my custom order.
Same thing for the prev method.

**Comment by rbnschlz** [comment]
Any chance for a quick fix? Much needed.

**Comment by texnixe** [comment]
If you need a quick solution, you could create a custom file method.

And regarding the enhancement label, everything that is not currently supported, is an enhancement, isn't it?

**Comment by rbnschlz** [comment]
any idea on how to get started with a custom file method? Could I possibly copy the logic of the next method for pages? If yes, were do I find it?

**Comment by jenstornell** [comment]
@rbnschlz Maybe this will help? https://getkirby.com/docs/developer-guide/objects/file

**Comment by texnixe** [comment]
As file method:

```
file::$methods['nextImage'] = function($file, $sort, $dir) {
  $siblings = $file->page()->images()->sortBy($sort, $dir);
  $index = $siblings->indexOf($file);
  $next = $siblings->nth($index+1);
  return $next;
};
```

Call:

```
$image = $page->images()->sortBy('sort', 'asc');
$next = $image->nextImage('sort', 'asc');
```
Note that in this simple example you have to pass the sort order and direction.
