### ISSUE TITLE
Language detection: Check all options in the Accept-Language header

### ISSUE THREAD

**Issue by jonabaptistella** [getkirby-v2/kirby#510]
I have also tried to activate this language switcher but I am not able to get it to work when I add Brazilian Portuguese. It worked with Norwegian and English. 

I have made a fresh install of the language kit and here it is: https://github.com/jonabaptistella/lang-switcher-test 

Nothing seems to do the trick here. Ideas?

**Comment by lukasbestle** [comment]
What exactly "doesn't work"? I can switch between the languages just fine. You are just missing a translation of the `site/languages/br.php` file and the content files.

**Comment by jonabaptistella** [comment]
That will be the `c::set('language.detect', true);` that is not doing it´s job. In my Brazilian Firefox it still give the english language. (I have fixed the missing file to make sure that is not causing this.) And I have deleted all cache. The same issue apply to the Norwegian language with Norwegian Firefox. 

![lang-auto-demo-error](https://cloud.githubusercontent.com/assets/2127627/20120865/c64c3124-a5f5-11e6-9515-8ae8b6e4739b.gif)

I have same issue in v.2.3.2 so I had a small hope that this was fixed in the new version 2.4.0. 
Also I have tried with different language codes. And nothing seem to fix this. So is it me that miss something here, or is this a bug? I am sorry for posting this here since I am not sure. I will not do that in the future.

**Here is the config file:**
```
c::set('languages', array(
  array(
    'name'    => 'English',
    'code'    => 'en',
    'locale'  => 'en_US.utf-8',
    'default' => true,
    'url'     => '/'
  ),
  array(
    'name'    => 'Portugues',
    'code'    => 'br',
    'locale'  => 'pt_BR.utf-8',
    'url'     => '/br'
  ),
  array(
    'name'    => 'Norsk',
    'code'    => 'no',
    'locale'  => 'nb_NO.utf-8',
    'url'     => '/no'
  )
));
```

**Comment by jonabaptistella** [comment]
@lukasbestle ops, I am still new to using github. Was not the meaning to close this case. And did the answer over fill in the needed info?

**Comment by jonabaptistella** [comment]
My mistake here... :/

**Comment by lukasbestle** [comment]
Sorry for the delay. I have just tested this with your test repo and can't reproduce it.

Have you verified that your Firefox installations actually have the `Accept-Language` header set to the respective languages? As far as I know, Firefox shares the profile between different installations, so just opening the other version won't change the value that gets sent to the server.

**Comment by jonabaptistella** [comment]
hi @lukasbestle I have checked now and it is set correct in each install so how shared profile. 

![screen shot 2016-11-15 at 15 14 07](https://cloud.githubusercontent.com/assets/2127627/20315842/91ab690c-ab46-11e6-9add-e7a1f111196a.png)
![screen shot 2016-11-15 at 15 12 50](https://cloud.githubusercontent.com/assets/2127627/20315843/91f70970-ab46-11e6-8a83-884020cb6a41.png)

So that mean that it should give the correct language...  But why doesn´t it happen automatic?

**Comment by lukasbestle** [comment]
Kirby checks the first choice of the browser against the language codes you set in the config. For Norwegian the code you set is sent by the browser as fourth choice, Brazilian Portuguese doesn't have a code `br` at all, it's always either `pt-br` or just `pt` for Portuguese.

I agree that this isn't optimal. Kirby should check all options in order and use the best available language. I have converted this issue to an idea for the future.

**Comment by jonabaptistella** [comment]
Even after adapting the code to the output in firefox and of course empty the cache several times, it´s still do not work. So I really hope on a much more robust auto switcher in the future. 

Here is what I changed this to:
```

c::set('languages', array(
  array(
    'name'    => 'English',
    'code'    => 'en',
    'locale'  => 'en_US',
    'default' => true,
    'url'     => '/'
  ),
  array(
    'name'    => 'Portugues',
    'code'    => 'br',
    'locale'  => 'pt-BR',
    'url'     => '/br'
  ),
  array(
    'name'    => 'Norsk',
    'code'    => 'no',
    'locale'  => 'nb-no',
    'url'     => '/no'
  )
));
c::set('language.detect', true);
```

**Comment by jonabaptistella** [comment]
Looking forward to see what you can come up with here @lukasbestle. 👍

**Comment by lukasbestle** [comment]
You need to change the code, not the locale.

**Comment by jonabaptistella** [comment]
@lukasbestle This is really not ideal. Cause that is reflected all over the place. And will also add issues with the content structure, right?

**Comment by jonabaptistella** [comment]
@lukasbestle ohh, I was not sure about that. I just installed a new copy of only Brazilian firefox on my wife's computer and she have never visited this test site before, and she still gets served the fallback language. Also I changed the code as you said. So I need to say I wish it was a little bit more docs on how Kirby read this and what is what in the config as well. Need to say I am a little confused since it did not work at new visiter. 

Just add the link to the config as is now: <https://github.com/jonabaptistella/lang-switcher-test/blob/master/site/config/config.php>

I know that this is not the easiest topic to make perfect but really hope this will be great. Also just so you know I use cloudflare for the domain I testing with. But it should pass-thru info and headers are sent are on.

**Comment by lukasbestle** [comment]
Yes, I agree with you that it isn't ideal for language variations like Brazilian Portuguese. If you use the code `pt`, it should be fine (after the fix I proposed above), but then you won't be able to differentiate between "normal" and Brazilian Portuguese of course.

Regarding the "it doesn't even work on a new browser" issue: Yes, as I said, we will need to fix this in Kirby by checking through all variations instead of just the first choice of the browser.
If it doesn't work at all in such cases, it also can't work for new visitors. ;)

**Comment by jonabaptistella** [comment]
Ok, @lukasbestle. I misunderstood you thought that I could use this by modifying the config now. Sorry. Looking forward to the fix. Thank you for great work!

**Comment by schnti** [comment]
A little hack is to disable the language detection `c::set('language.detect', false);` and add an new route

```
kirby()->routes(array(
	[
		'pattern' => '/',
		'action' => function () {

			$lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
			switch ($lang) {
				case "de":
					go('de');
					break;
				case "en":
				default:
					go('en');
					break;
			}
		}
	]
));
```

What do you think?

**Comment by jonabaptistella** [comment]
Is this implemented yet?

**Comment by jonabaptistella** [comment]
Hi @schnti I have not seen your comment. I am sorry. I tried the code in my current project and it does not seem to work for me.

**Comment by lukasbestle** [comment]
No, this is not yet implemented. We are currently working on the multilang implementation in Kirby 3 that will hopefully be a bit more robust than the implementation in Kirby 2.

**Comment by lukasbestle** [comment]
@schnti's hack also only checks the first choice of the browser. A more reliable fix (that can probably also be used in a hack like this) would probably be to split the header value by comma and then check for each value if it is a valid language for the current site.

**Comment by jonabaptistella** [comment]
I resolved it with .htaccess for the moment like this. And that gave me the the option to also hack the pt-br language tag to get it to redirected to the `/br`. 

https://forum.getkirby.com/t/automatic-language-detection-bug/11023/4?u=jonabaptistella

**Comment by jonabaptistella** [comment]
Sorry, for closing this. Hit the wrong button.

**Comment by francisceril** [comment]
Is this issue been resolved already?
`c::set('language.detect', true);` doesn't work as well for me. May be I'm just missing something.

If not resolved, what would be the best work around?

**Comment by jonabaptistella** [comment]
Hi, I don´t think so. For the v3 of Kirby I guess it will be more robust. I found this work around here: https://forum.getkirby.com/t/automatic-language-detection-bug/11023/4?u=jonabaptistella

Hope that helps. 👍
