### ISSUE TITLE
$page->content()->exists() is true for page with no text file

### ISSUE THREAD

**Issue by fvsch** [getkirby-v2/kirby#527]
Hi. Maybe I’m misunderstanding what `Content::exists` is supposed to do. I’m looking for a way to tell if a page has a text file, and tried `$page->content()->exists()`, but it returns true for an empty folder.

For an empty folder:
- `$page->content()->root` is set to the folder's path.
- `$page->content()->exists()` checks that this folder exists.

Is that the intended behavior? Maybe `$page->content()->exists()` checks if there is a directory for that page where files may be written to?

I tried checking if a content file exists by using `$page->inventory()['content']`, but this is formatted in different ways for single-language and multilingual sites, so the check is a bit tricky, and I was hoping there was a more built-in way.

**Comment by fvsch** [comment]
Looking at the implementation, I expected this implementation:

```php
  /**
   * Checks if the content file exists
   *
   * @return boolean
   */
  public function exists() {
    return file_exists($this->root . DS . $this->name);
  }
```

instead of:

```php
  /**
   * Checks if the content file exists
   *
   * @return boolean
   */
  public function exists() {
    return file_exists($this->root);
  }
```

**Comment by lukasbestle** [comment]
`$this->root` already points to the file, not to the content directory as you can [see here](https://github.com/getkirby/kirby/blob/master/core/content.php#L37).

However it's interesting that Kirby creates a Content object with the root set to the content directory if the file does not exist. This shouldn't happen.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
