### ISSUE TITLE
Registering any model breaks programmatic page creation

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/kirby#528]
See https://github.com/getkirby-plugins/modules-plugin/issues/11.

This is a really strange issue. See the details in the other issue to be able to reproduce this and [my comment](https://github.com/getkirby-plugins/modules-plugin/issues/11#issuecomment-268198545) regarding first ideas where this might come from. I wasn't able to find the origin though.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
