### ISSUE TITLE
Routes default to GET, but HEAD should return the same

### ISSUE THREAD

**Issue by sebsel** [getkirby-v2/kirby#538]
If someone sends a HEAD request, it should return the same headers as a GET request. But if the request goes through Kirby's router, the GET can return 200 but the HEAD 404.

So routes should default to `'GET|HEAD'` instead of `'GET'`.

https://getkirby.com/docs/developer-guide/advanced/routing#methods

**Comment by lukasbestle** [comment]
That's a good point. But then the HEAD requests would also return the response body of the GET route. I think we should have some special check instead: If the request is a HEAD request and there is no explicit route defined, call the GET route but discard the body.

**Comment by sebsel** [comment]
Nope, it already works! The following link didn't show up when [Tantek sent a HEAD request](https://chat.indieweb.org/dev/2017-01-12#t1484185595027000):
https://seblog.nl/2017/01/11/1/homebrew-website-club

I now added `'method' => 'GET|HEAD'` to the route and that works just fine. When I send a HEAD-request, the body is gone.

So I guess it's just adding `'GET|HEAD'` to the defaults?

**Comment by sebsel** [comment]
Yep, turns out this is a toolkit-thingy.
When you change [this line](https://github.com/getkirby/toolkit/blob/master/lib/router.php#L115) to:
```php
      'method'    => 'GET|HEAD',
```
It's solved!

![schermafbeelding 2017-01-16 om 14 16 14](https://cloud.githubusercontent.com/assets/16517999/21984470/5d470438-dbf6-11e6-862d-616d80788b7d.jpg)

Will file the issue there.

**Comment by lukasbestle** [comment]
Seems like either PHP or Apache discard the body then. :)

**Comment by sebsel** [comment]
Yeah, I couldn't find it in the Kirby code indeed... the next question is: do you want a backup for when PHP or Apache don't handle the HEAD correct? :)

**Comment by Zegnat** [comment]
> Seems like either PHP or Apache discard the body then. :)

Also note that if it is Apache discarding the body, you would need to test other servers like nginx separately. This could open Kirby up to a whole other can of worms.

**Comment by lukasbestle** [comment]
Yes, exactly. Responses to HEAD requests that have a body are a no-go.

**Comment by sebsel** [comment]
(why is this not a bug? :P)

I was thinking about it some more, and thought: HEAD should probably be a variant of GET. If someone sets the method to 'GET|POST', not aware of HEAD's existence, it will 404 again on HEAD requests, so my solution is indeed no solution.

**Comment by lukasbestle** [comment]
That's a good point. Actually this is the definition of HTTP HEAD. I don't think there is ever a situation where the headers of a HEAD response should differ from those of the respective GET response.

**Comment by Zegnat** [comment]
> I don't think there is ever a situation where the headers of a HEAD response should differ from those of the respective GET response.

[The HTTP 1.1 spec](https://www.ietf.org/rfc/rfc2616.txt) agrees with you, HEAD and GET responses for the same URL should be identical apart from the missing message body:

```
9.4 HEAD

   The HEAD method is identical to GET except that the server MUST NOT
   return a message-body in the response. The metainformation contained
   in the HTTP headers in response to a HEAD request SHOULD be identical
   to the information sent in response to a GET request.
```
