### ISSUE TITLE
Accessing files with $page->url() + filename does not work in multilang environment

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#547]
https://forum.getkirby.com/t/file-urls-change-when-pages-are-moved-or-made-invisible/5348

Without using URL-Keys, the link reroutes to the default language URL, with URL-Keys you end up with a 404.

**Comment by lukasbestle** [comment]
We will probably need to refactor the multilang routing anyway, so not hacking in any temporary fixes here.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
