### ISSUE TITLE
Include Composer autoloader if it exists

### ISSUE THREAD

**Issue by mzur** [getkirby-v2/kirby#555]
If there is a file `vendor/autoload.php` in Kirby's root directory, Kirby should automatically include it ([thread in the forum](https://forum.getkirby.com/t/plugin-developers-convention-for-installation-via-composer/6626/21?u=mzur)). I suggest something like this:

```php
try {
   include_once 'vendor'.DS.'autoload.php';
} catch (ErrorException $e) {
   // never mind
}
```

**Comment by lukasbestle** [comment]
What kind of Exception could occur while loading the file besides the file not existing (which should better be checked beforehand)?

**Comment by jenstornell** [comment]
If this is implemented and I use like 40 plugins and don't use Composer, how much does this cost in terms of performance? Does it need to check for this file in every plugin in on every pageload?

**Comment by texnixe** [comment]
> and I use like 40 plugins

Then you have a problem anyway…

**Comment by lukasbestle** [comment]
No, there is only one of those files per site, not per plugin. So it's fine regarding performance.

**Comment by mzur** [comment]
The `ErrorException` is thrown if the file does not exist. The posted code should behave similar to a `file_exists` combined with a `require` but I thought this might be more performant.

But come to think of it the try/catch may not be such a good idea after all. If static files are loaded and throw some kind of `ErrorException` these would be silently ignored as well.

**Comment by lukasbestle** [comment]
Exactly, so I think we should do it like this:

```
$composer = kirby()->roots()->index() . DS . 'vendor' . DS . 'autoload.php'.
if(is_file($composer)) require_once($composer);
```

This code should be part of the plugin loading process.

**Comment by fvsch** [comment]
Should the composer root be configurable?

```php
// in kirby/roots.php
public function vendor() {
  return isset($this->vendor) ? $this->vendor : $this->index . DS . 'vendor';
}

// In the plugin loading process
$composer = kirby()->roots()->vendor() . DS . 'autoload.php';
if(is_file($composer)) require_once($composer);
```

This would allow overriding the location of the vendor directory in `site.php` (or `index.php` if you’re changing it directly), if needed.

**Comment by lukasbestle** [comment]
What would be the use-case for this? Are there situations in which the vendor directory is somewhere else?

**Comment by fvsch** [comment]
> What would be the use-case for this?

Same as the use cases for [having the `site` directory somewhere else than the default location](https://getkirby.com/docs/developer-guide/configuration/folders), I guess. Thinks like:

- multi-site instances;
- keeping the vendor dir outside of the public web root.

It would be strange to have all main folder locations (content, site, thumbs, kirby, templates, plugins, cache…) be configurable, but make this one hard-wired.

**Comment by lukasbestle** [comment]
Good point.

**Comment by Zegnat** [comment]
Do note that the vendor directory path is [configurable in composer](https://getcomposer.org/doc/06-config.md#vendor-dir), so it would only be proper for Kirby to include it from a configurable path as well.
