### ISSUE TITLE
Return something from the hooks

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/kirby#556]
The panel is using hooks but plugin developers can use hooks as well. Sometimes it means problem when they don't return anything.

**Real case example**

I needed to use output buffering and I'm not too fond of that.

```php
<?php
class LogicField extends BaseField {
	public function input() {
		ob_start();
		kirby()->trigger('pluginLogicField', array(
			$this,
			$this->page(),
		));
		$out = ob_get_contents();
		ob_end_clean();

		return $out;
	}
}
```

**Source:** https://github.com/jenstornell/kirby-logic-field

**Comment by lukasbestle** [comment]
Just for reference: What we would need to do is to always return an array of return values from `kirby()->trigger()` as there can be multiple hooks of the same type.
