### ISSUE TITLE
$page->files() returns a files objects, while $page->children()->files() returns a collection object

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#565]
I just realized this when trying to implement a custom files method and wondering why the method didn't deliver any results… :thinking: As a consequence, none of the files method work. Wouldn't it make sense if the files methods also worked with a collection of files that is not tied to a page?

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
