### ISSUE TITLE
Multilang: language not yet set when plugin runs

### ISSUE THREAD

**Issue by distantnative** [getkirby-v2/kirby#566]
I just encountered that in a multilang site, the current language seems not yet to be set when running a plugin. With `site/plugins/test/test.php`:

```php
<?php
var_dump(site()->language());
```

It still puts out the default language, while the same `var_dump` shows the correct current language (matching the current URL) when called e.g. from the footer snippet of the starterkit.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
