### ISSUE TITLE
feature request : sort files like subpages in blueprint

### ISSUE THREAD

**Issue by judbd** [getkirby-v2/kirby#568]
It would be nice to have the abilty to sort files in panel (via page blueprint) like the subpages to reflect the frontend sorting.

example:

```
files:
  sortable: true
  sort: isarchive asc filename desc
```

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
