### ISSUE TITLE
panel could check if session is still valid

### ISSUE THREAD

**Issue by bnomei** [getkirby-v2/kirby#572]
**story**
did some work in the panel. saved. switched tab. lunchbreak. returned to tab. entered some more text. presses save. BAM. input gone – redirect to login page.

**solution**
maybe the panel could have a js timer or ajax check if session still exists and present a modal warning (will redirect to login) when session has ended.

**Comment by jenstornell** [comment]
[Fingerprint](https://github.com/jenstornell/kirby-secrets/wiki/Fingerprint) is one thing that helps a bit on the way.

I'm not sure that an ajax would be a great idea. It means many requests to the server and the modal would not appear directly when logged out which means it's kind of a false safety.

Two ideas comes to mind:

- Autobackup the data from the session to a text file somewhere on save, even if logged out. That way no data will be lost.
- Don't auto logout on save even if session has expired. Instead give an error message that the user has been logged out. It gives the chance to copy the data from the fields and use it when logged in again.

For the second suggestion, I think it could be nice to relogin from the current panel page, not leaving the panel page.

**Comment by bnomei** [comment]
its about not being informed that the panel session is gone and less about saving data.
what i meant was that while a panel view is open and text can be entered 

- the session should stay alive or 
- if session is not live anymore (ajax check) the panel warn user and prevent him from entering data that will be lost anyway.
