### ISSUE TITLE
js() css() allow filename modification for @auto

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby-v2/kirby#584]
I have gzipped template specific scripts.
```php
  <?= js(c::get('gzip', false) ? 'assets/scripts/commons.js.gz' : 'assets/scripts/commons.js'); ?>
  <?= js('@auto'); ?>
```
It would be pretty handy to have the option to override the default filename.

**Ideas**
- Add an option. Something like this: `c::set('auto.js.filename', '{name}.js.gz');`
- Add a extra parameter to the helper function
- Some extra syntax in the `@auto` string. `js('@auto:{name}.js.gz');` (kinda ugly)
- Or perhaps the option to add a ending like `js('@auto.js.gz');` or only `js('@auto.gz');`

**Comment by HashandSalt** [comment]
Get's our vote 👍

**Comment by lukaskleinschmidt** [comment]
For reference
https://forum.getkirby.com/t/minified-and-cachebusted-js-helper-output/7705

**Comment by lukasbestle** [comment]
Why do your gzipped files have a `.gz` extension and why are you linking to that file depending on a config variable?
Most workflows I have seen decide on the encoding per request depending on the `Accept-Encoding` header.

**Comment by HashandSalt** [comment]
Can't answer the `.gz` question....

Linking through a variable is so that minified code can be loaded through the helper via a live domain specific config file.

**Comment by lukaskleinschmidt** [comment]
Actually I have never even considered dropping the `.gz`. I am just used to it I think.
Thanks for the feedback.

**Comment by lukasbestle** [comment]
That's a good point, we might consider this.

**Comment by lukaskleinschmidt** [comment]
@lukasbestle  you are right. My code does not make sense. I somehow had a weird view of mod_deflate. 😅
