### ISSUE TITLE
Irregularly Maintenance/Offline Page occurs 

### ISSUE THREAD

**Issue by Mojo90** [getkirby-v2/kirby#592]
On my productive environment site I use sometimes there occurs the Maintenance/Offline Page. Of course on my production site I have debug set to false so this site occurs. But why does this happen? If the page is refreshed directly it does not occur again. Normally it does never occur 2nd times in a row. Are there any known issues what can reproduce this?
Because I think it is now error in my Application code otherwise it would occur all the time for a certain page I think (of course I had lots of these in development and have debug set to true so that I can catch the issue, but in prod there shouldn't be one...)
Any help highly appreciated!

**Comment by texnixe** [comment]
Do you mean the Whoops error page?

If your error settings are correctly set, any php errors should still be logged in the php error logs file.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
