### ISSUE TITLE
Encrypted email ? (Html source)

### ISSUE THREAD

**Issue by starckio** [getkirby-v2/kirby#60]
Ex:

```
<yourmail@website.com>
```

Return:

```
<a href="mailto:yourmail@website.com">yourmail@website.com</a>
```

Sorry if I'm in the wrong category.
Thank.

**Comment by MrApe** [comment]
Using (email: some@mail.com) still does not encrypt.

**Comment by texnixe** [comment]
If you look at the source code, you will see that it is encrypted.

**Comment by MrApe** [comment]
I'm sorry. Inspecting the element in Safari or Chrome does in fact show the unencrypted address. retrieving the page with curl shows encryption when using '(email: ...)'. Thanks a lot.
