### ISSUE TITLE
'segmentation fault' when trying to load plugin asset

### ISSUE THREAD

**Issue by aaronschmied** [getkirby-v2/kirby#625]
I've been experiencing some kind of weird error, I've never encountered before:
When trying to install the [kirby-analytics-dashboard](https://github.com/gearsdigital/kirby-analytics-dashboard) plugin, kirby couldn't load the asset files. 
It seemed to prepent a `<` char in the js asset file.

response body of request to `assets/plugins/kirby-analytics-dashboard/js/dist/index.js`:
```
<require=function(r,e,n){ ...
```

file content of `site/plugins/kirby-analytics-dashboard/assets/js/dist/index.js`:
```
require=function(r,e,n){ ...
```

I replaced the content of the file and the `<`char vanished, so it must have something to do with the files content.

I also tried to serve it using only the `kirby/toolkit`'s `Response` class:
``` php
<?php

require('kirby/vendor/getkirby/toolkit/bootstrap.php');

$fileRoot = "site/plugins/kirby-analytics-dashboard/assets/js/dist/index.js";

echo (new Response(f::read($fileRoot), f::extension($fileRoot)));
```
It worked without the error.

I assume the error has something to do with kirby itself, since:
- The plugin has no executed code in this request
- The file seems to be ok, since it's returned correctly when accessed via a standard request
- When omitting kirby and just using the same toolkit version it works as well

# How to reproduce

I downloaded the kirby starterkit:
https://github.com/getkirby/starterkit/archive/2.5.8.zip

and the plugin:
https://github.com/gearsdigital/kirby-analytics-dashboard/archive/v1.0.2.zip

Installed the plugin into the `sites/plugin` folder and started (enabled the panel) and started the php integrated webserver using `php -S 0.0.0.0:8080`

I tested it on different webservers / php versions, it always occured

When trying to access the before mentioned `assets/plugins/kirby-analytics-dashboard/js/dist/index.js`, php crashes with the following output:
```
[1]    23171 segmentation fault  php -S 0.0.0.0:8080
```

**Comment by gearsdigital** [comment]
@aaronschmied Did you have any other plugins installed? Your issue could be related to [Unexpected token < if kirby-html-minifier is installed](https://github.com/gearsdigital/kirby-analytics-dashboard/issues/5).

**Comment by aaronschmied** [comment]
Well, yeah i had the kirby-html-minifier installed on my project where it occured first, but it also happens when installing just the mentioned plugin using the starter kit.

**Comment by ca057** [comment]
Without any plugins installed, I get the same error when working with the panel. As soon as it's trying to load `/panel/assets/js/dist/panel.min.js?v=2.5.11`, it's crashing with the simple line:
`Segmentation fault (core dumped)`
Does anyone has a solution?

**Comment by bzgeb** [comment]
> 
> 
> Without any plugins installed, I get the same error when working with the panel. As soon as it's trying to load `/panel/assets/js/dist/panel.min.js?v=2.5.11`, it's crashing with the simple line:
> `Segmentation fault (core dumped)`
> Does anyone has a solution?

I have this same seg fault every time I try to open the panel.  All I did was download and run the kirby starterkit.

**Comment by jonathan-reisdorf** [comment]
I have this weird error now as well. When I tell the panel to load 2 assets less, e.g. by changing `panel/app/src/panel/controllers/base.php` line 68 and 69 to
```
        $defaults['pluginscss'] = '';
        $defaults['pluginsjs']  = '';
```
I get no get fault anymore (also works to disable two other assets of that controller)

**Comment by jonathan-reisdorf** [comment]
I've reproduced the behavior on two different machines now, both running the PHP 7.2 built-in server, both linux. Until version 2.4.1 everything works, from 2.5.0 I get the segmentation fault in the panel.

**Comment by jonathan-reisdorf** [comment]
New observation: I don't have segmentation faults with any 2.5.x version as long as I have one field in the site/fields folder (doesn't matter which one)

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
