### ISSUE TITLE
Memory allocation error on the page

### ISSUE THREAD

**Issue by introvert** [getkirby-v2/kirby#629]
We are using kirby for our blog, and in some cases when I visit the index page it sometimes throws the following error:

    Fatal error: Out of memory (allocated 786432) (tried to allocate 12288 bytes) in /nfs/c12/h04/mnt/.../kirby/vendor/getkirby/toolkit/lib/email.php

Any idea why could that be?

**Comment by texnixe** [comment]
Your script runs out of memory. What are your memory_limit settings in your php.ini? What is your script doing?

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
