### ISSUE TITLE
`not()` doesn't work properly in multilang setting if URL-Key is used

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#631]
https://forum.getkirby.com/t/is-there-a-way-to-get-filterby-template-mytemplate-work-on-a-multilang-site/9656/25

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
