### ISSUE TITLE
Routing: `$page` and `page()` return different page objects

### ISSUE THREAD

**Issue by tillprochaska** [getkirby-v2/kirby#633]
When using custom routes, the value of the global `$page` variable will be different from the value `page()` is returning in templates.

To reproduce, set up a page and a custom route like this:

```php
kirby()->set('route', [
    'pattern' => '/debug',
    'method' => 'GET',
    'action' => function($slug) {
        return page('test-page');
    },
]);
```

Template:
```php
<?php

var_dump($page);
var_dump(page());
```

**Comment by texnixe** [comment]
If you use
```
return site()->visit('test-page');
```
you should get the same result.

**Comment by lukasbestle** [comment]
Yep, that's currently the way to go.

The question is: Should we change the docs or should we implement automatic visiting of the page if just a page is returned?

**Comment by tillprochaska** [comment]
Thanks @texnixe and @lukasbestle! The solution from the comments above works for me in the meantime!

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
