### ISSUE TITLE
Excerpt function dots inconsistency

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/kirby#639]
https://getkirby.com/docs/cheatsheet/helpers/excerpt

**Example 1:**

It gives `…` when it's too long. The dots here is one single character.

```php
<?= excerpt($page->text(), 300) ?>
```

**Example 2:**

It gives `...` when it's too long. The dots here are many characters.

```php
<?= excerpt($page->text(), 20, 'words') ?>
```

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
