### ISSUE TITLE
Nested route and page model causing error

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#640]
When omitting parent folders via a route and the pages on these different levels use the same template, adding a page model that modifies the URL method causes an error (PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Users/xxx/htdocs/kirby-2/kirby/vendor/getkirby/toolkit/lib/url.php on line 266).

Steps to reproduce:

Create a folder structure like this:

```
- parent-page with template a.php
    -- child-page with template a.php
        ---- grandchild with template a.php

```

Route:

```
c::set('routes', array(
  array(
    'pattern' => '(:any)',
    'action'  => function($uid) {

      $page = page($uid);

      if(!$page) $page = page('parent-page/' . $uid);
      if(!$page) $page = page('parent-page/child-page/' . $uid);

      if(!$page) $page = site()->errorPage();

      return site()->visit($page);
    }
  ),

  array(
    'pattern' => '(:all)/(:any)',
    'action'  => function($uri,$uid) {
      go($uid);
    }
  )
));
```

Model:

```
<?php

class aPage extends Page {
  function url() {
    return url($this->uid());
  }
}
```

The error occurs when the model is added.

This can of course be worked around by using different templates/models for the subpages.

**Comment by rodrigogalindez** [comment]
I confirm I can reproduce this issue in my installation. Any bug fixes?

**Comment by rodrigogalindez** [comment]
Hi guys, any news about this? It's still showing up in my installation :-(

**Comment by texnixe** [comment]
I actually think that this won't get fixed in K2. It is really an edge case and can easily be worked around by either using different templates/models or using a custom page method for the url instead of a model.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
