### ISSUE TITLE
Parsedown Extra Footnotes not working since 2.5.10

### ISSUE THREAD

**Issue by wottpal** [getkirby-v2/kirby#641]
Hey,

I've just found an issue with one of my sites which I've updated to 2.5.10 recently. The footnotes are embedded as plain text and the HTML is not parsed. (see screenshots)

In Kirby 2.5.9:
<img width="254" alt="kirby 2 5 9" src="https://user-images.githubusercontent.com/3930150/38870104-15af9630-424d-11e8-8a92-4eed7f5ab17d.png">

In Kirby 2.5.10:
<img width="826" alt="kirby 2 5 10" src="https://user-images.githubusercontent.com/3930150/38870105-15cb45a6-424d-11e8-8e39-8742af6ec1e5.png">

I did not have the time yet to reproduce this on a plain starterkit but I will if this helps. But maybe the issue is obvious for you.

Thanks, 
Dennis

**Comment by wottpal** [comment]
Okay I've located the according issue https://github.com/erusev/parsedown-extra/issues/118. I will bump this thread when the issue is fixed in parsedown-extra!

**Comment by judbd** [comment]
I just had the same problem, update to last version of [parsedown](https://github.com/erusev/parsedown/releases/tag/1.7.4) and [parsedown extra](https://github.com/erusev/parsedown-extra/releases/tag/0.8.1) in `/kirby/vendor/erusev` folder seems to have fixed it. It'll be great if this patch is included in the last version of kirby 2!

Note: You may have to re-save your page in panel for re-render the faulty footnotes.
