### ISSUE TITLE
Feature: Aria Attributes for Markdown links

### ISSUE THREAD

**Issue by marcobiedermann** [getkirby-v2/kirby#645]
I would suggest to also allow for adding additional ARIA attributes to any link in markdown.
For now, it is limited to these attributes: https://forum.getkirby.com/t/adding-markdown-link-attribute-problem-with-styling-in-textfield/9559
From what I've found [here](https://github.com/GoogleChrome/lighthouse/issues/4494) it is preferred to use `aria-label` instead of `title` on links.

**Comment by fvsch** [comment]
Do you have a use case for using `<a aria-label>` in rich text content?

I tend to use `aria-label` for some links and buttons in UI code, especially for links and buttons that only contain a SVG icon, but have not needed this attribute for content links before.

**Comment by marcobiedermann** [comment]
Yes, for example, I have a field in the backend panel to enter text for the cookie disclaimer you see on most pages.
In the text is says something like this:
> Get more information [here]()

In my `aria-label` I would like to put in

> about cookie regulations.

So in the end, the text is not visual but for a screenreader it reads like this:

> Get more information about cookie regulations

Just as an example.
I thought in the first place to use the title attribute on links but screenreaders do not encounter this.

**Comment by texnixe** [comment]
If would probably make sense to replace "here" with something more telling even for non-screen reader users?

**Comment by marcobiedermann** [comment]
@texnixe Yes and not. Sometimes you have to fight with designers or content creators :P

**Comment by fvsch** [comment]
I would argue that your “here”, with `title` or without any extra attribute, *is* accessible. It’s bad writing and usability, yes, but it’s the same bad usability for everyone regardless of disability. 😛 

We should note that the value of `aria-label` replaces the text content. This can result in nonsensical sentences when the link is inside text.

Using `aria-label` for links like “Read more” makes more sense for links that are their own paragraph, e.g. in an article teaser with a title, text preview and call to action. (If those links are duplicating another link that comes before it, maybe a link on the title, you could also use `aria-hidden="true"` to hide them from screen readers altogether.)

**Comment by marcobiedermann** [comment]
@fvsch Thank you very much for your explanation and I absolutely get your point and also agree about you that in any case it is a content issue.

Still I think it would not hurt to allow `aria-label` attribute in your backend textarea fields.

Would there be a way to allow all additional attributes to a link? This way you can add pretty much anything like classes, data attributes, aria attributes and so on.
So far I do not see any security issues with that because the string is still sanitized by the `kirbytext()` method or am I missing something?

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
