### ISSUE TITLE
$site->user() doesn't work

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby-v2/kirby#647]
Tried this example from the manual in my template "home.php":
`<?= $site->user()->current() ?>`

Result:
`Call to a member function current() on boolean`

Kirby Toolkit | v2.5.10
Kirby CMS | v2.5.10

**Comment by flokosiol** [comment]
Doesn’t sound like a bug to me. If you’re not logged in, `$site->user()` won’t return a user object and because of this the `current()` method isn’t available. 

I think you first need to check for a user …

```
<?php
if ($site->user()) {
  // ...
}
?>
```

**Comment by bavarianbytes** [comment]
I put that in my template:
`
	<?php
	if ($site->user()) {
		echo "loggedin";
	}
	?>
`
No output of "loggedin", while i'm logged in via the Panel.

**Comment by texnixe** [comment]
That's strange. Have you checked your source code?

**Comment by bavarianbytes** [comment]
What should I check?

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
