### ISSUE TITLE
Checkboxes columns seems not to be implemented

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/kirby#649]
Columns does not seem to be implemented.

```php
category:
    label: Category
    type: checkboxes
    columns: 3
    options:
      my_option1: One
      my_option2: Two
      my_option3: Three
```

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
