### ISSUE TITLE
Model not defined on page create in multi language setup

### ISSUE THREAD

**Issue by georgobermayr** [getkirby-v2/kirby#650]
Hi,

When I create a new page in a multi language setup the page model is not correctly defined by the create function:

```
$template = 'mytemplate';
$newPage = site()->pages()->create($pagePath, $template, $pageContent);
```

In `branches/mulilang/pages.php` the create function adds a language code to the template:

```
static public function create($uri, $template, $data = array()) {
  return parent::create($uri, $template . '.' . site()->defaultLanguage->code, $data);
}
```

So `$template` is now `mytemplate.en`. 

Then the basic create function `parent::create`` is unable to find the model: 

```
if(isset(static::$models[$template])) {
  $model = static::$models[$template];
  $page = new $model($page->parent(), $page->dirname());
}
```
since `static::$models` refers to `mytemplate`. So I guess we need to stripe out the language code from the template string here again?

Kind regards,
Georg

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
