### ISSUE TITLE
Support official YAML extension for languages

### ISSUE THREAD

**Issue by mxdvl** [getkirby-v2/kirby#657]
It seems that `site/languages/en.yml` should support `.yaml` extensions, as the [YAML FAQ](http://yaml.org/faq.html) suggest it’s the proper one. I believe the fix is in the following line:

https://github.com/getkirby/kirby/blob/e3bc4e4277859249cff1a67c333a5544766cad31/kirby.php#L535

**Comment by lukasbestle** [comment]
Good idea! As the `.yml` extension is also very common and to ensure backwards-compatibility, I'd say it would be best to support both extensions. What do you think?

**Comment by mxdvl** [comment]
Absolutely agreed it should support both extensions. But the fact that it currently only supports a non-recommended extension for YAML files is problematic. I believe that this behaviour is only exhibited in the languages folder, as blueprints work with both extensions. Maybe something to double check in the upcoming Kirby 3, too!

**Comment by mxdvl** [comment]
Sorry, still an open issue!

**Comment by lukasbestle** [comment]
I can't say yet if we'll be able to fix this in Kirby 3.0.0, but very soon after. I've already created an issue in our Kirby 3 repo. :)
