### ISSUE TITLE
SERVER_NAME list breaks sanitize

### ISSUE THREAD

**Issue by scaccogatto** [getkirby-v2/kirby#662]
I found that, if you have a list as `SERVER_NAME` (happens frequently in a `nginx` environment) Kirby just breaks.
This is because the `sanitize` function treats `SERVER_NAME` in the same way he treats `HTTP_HOST`.

Here a link to the broken function:
https://github.com/getkirby/kirby/blob/e3bc4e4277859249cff1a67c333a5544766cad31/vendor/getkirby/toolkit/lib/server.php#L46

I am building a PR right now but I think we should discuss if taking the first list value is ok or we should declare it in some way.

**Comment by quamm** [comment]
> If `SERVER_NAME` is defined as a list, it means that it's the list of all configured hostnames. The current hostname is not necessarily the first in that list, so I think it won't help to split the `SERVER_NAME` and pick any arbitrary item of the list.
> 
> Pretty much the only thing the user can do is to manually configure the base URL with the `url` option. Or is there another `$_SERVER` variable in your setup that more accurately defines the current hostname and that we could use for the automatic detection?

Setting the `url` option in the config file does not help. I think we should refactor the redirect condition at this point, maybe we should also do this for ports: it hides them if they are `80` or `443`. I think everyone should be able to decide the exposed port (especially now that a lot of people are using containers, docker and k8s). Let me know if you think this is a good idea.

**Comment by lukasbestle** [comment]
> Setting the url option in the config file does not help.

Why is that? The `url` option should always override the detected base URL when used.

> I think everyone should be able to decide the exposed port (especially now that a lot of people are using containers, docker and k8s).

I don't think so. Even if you are using several layers of reverse proxies, the URL to use should always be the one that the visitor sees. And that one hardly never contains the port unless that's required (which it isn't for 80 and 443).

**Comment by scaccogatto** [comment]
> > Setting the url option in the config file does not help.
> 
> Why is that? The `url` option should always override the detected base URL when used.
It overrides incorrectly using the language detector, leading into a infinite redirect loop. My pull request solves this problem.
> 
> > I think everyone should be able to decide the exposed port (especially now that a lot of people are using containers, docker and k8s).
> 
> I don't think so. Even if you are using several layers of reverse proxies, the URL to use should always be the one that the visitor sees. And that one hardly never contains the port unless that's required (which it isn't for 80 and 443).
If I use `8080` internally for example, Kirby (with language detector enabled) goes to `https://www.example.ext:8080/...` replying a `500` error.

**Comment by lukasbestle** [comment]
> It overrides incorrectly using the language detector, leading into a infinite redirect loop.

Ah, that makes sense. That's a bug in the language detector then. We have rewritten it in Kirby 3, maybe that will fix it.

> My pull request solves this problem.

Not really, as it will only work if the current domain is by chance the first of the list. It will break for all of the others.

> If I use 8080 internally for example, Kirby (with language detector enabled) goes to https://www.example.ext:8080/... replying a 500 error.

Same here. I think the language detector should always use the external domain (the one defined in the config if it can't be auto-detected properly like in your case).

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
