### ISSUE TITLE
$site->breadcrumb() creates duplicate links in non-default language

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#664]
This happens only if the home folder is removed and URL-Keys are used for the non-default language.

To reproduce:

1. in a langkit, set the homepage to, for example, blog.
2. add breadcrumb code in header
3. visit a subpage of blog in the non-default language (up to here, it works as expected)
4. now add URL-Key in non-default language, visit subpage of blog in non-default language again.
5. The link to `blog` appears twice in the breadcrumb navigation.

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
