### ISSUE TITLE
Support PHP 7.3?

### ISSUE THREAD

**Issue by anselmh** [getkirby-v2/kirby#667]
Hi,

is there any plan to support PHP7.3 with Kirby v2?
It is broken due to the changes with `compact()` in the latest PHP release.

Thanks for any information.

**Comment by bastianallgeier** [comment]
Yes, definitely! Do you have more info about the issues you are running into?

**Comment by anselmh** [comment]
🤦‍♂️ So, that’s good to hear that you would. But I just realized that the cases that triggered the error are from my own controller. For reference, [the issue is with `compact()` which now does throw an error if the variable is undefined](https://wiki.php.net/rfc/compact) which was different for PHP <7.3.

**Comment by bastianallgeier** [comment]
Ahhh, that's good to know. I was already wondering where we use compact at all. I use it often in examples, but never really in core code.
